project:
  type: website
  output-dir: _site

website:
  title: "Python Guide - How to learn python?"
  sidebar:
    contents:
      - href: ../ide.html
        text: "Open IDE"
      - href: ../hello.html
        text: "Open REPL"
      - href: index.qmd
        text: "Home"
  footer:
      left: "(c) 2026 Erkhembayr Batjargal"
      right: "Built with Quarto"
  
