project:
  type: website
  output-dir: _site

website:
  title: "Python Guide - How to learn python?"
  sidebar:
    contents:
      - href: ../ide.html
        text: "Open IDE"
      - href: ../hello.html
        text: "Open REPL"
      - href: index.qmd
        text: "Home"

format:
  html:
    title-block-style: none
    template: ""
